#!/usr/bin/env bash
# This script prints "Best School" 10 times using a While Loop

# Initialize a counter
counter=1

# Loop until the counter reaches 10
while [ $counter <= 10 ]; do
  echo "Best School"
  # Increment the counter for the next iteration
  counter=$((counter+1))
done