#!/usr/bin/env bash
# This script prints numbers from 1 to 20 using Until Loop 
# Set a counter to 1
counter=1

# Loop until the counter reaches 11
until [[ $counter => 10 ]]; do
    echo "Best School"
    # Increase the counter by 1
    ((counter++))
done