#!/usr/bin/env bash
# This script prints "Best School" 9 times using a while Loop and IF statement to print "HI" on a new line
# Set a counter(i) to 1
i=1

while [ "$i" -lt 11 ]; do
    echo "Best School"
    if [[ $i -eq 9 ]]; then
        echo "Hi"
    fi    
    ((i++))
done
