#!/usr/bin/env bash
# This script prints using a while Loop and if, elif and else statement.

# Set a i to 1
i=1
while [ "$i" -lt 11 ]; do
    
    if [[ $i -eq 4 ]]; then
        echo "bad luck"
    elif [[ $i -eq 8 ]]; then
        echo "good luck"
    else 
        echo "Best School"
    fi 
    ((i++))          
done
