#!/usr/bin/env bash
# list directory content in a List format
# Loop through all files in the current directory
for file in *; do
    # Check if the file is not a hidden file (does not start with '.')
    if [[ ! "$file" =~ ^\. ]]; then
        # Extract the part after the first dash and print it
        echo "${file#*-}";
    fi
done