#!/usr/bin/env bash


# Check if the file "school file" exists or "empty" or "regular file"
if [ -f "school" ]; then {
    echo "school file exists"

    if [ -s "school" ]; then {
        echo "school file is not empty"
    } else {
        echo "school file is empty"
    }

    if [ -f "school" ]; then {
        echo "school file is a regular file"
    }
} else {
    echo "school file does not exist"
};